export const mockupData = {
    "data": [
        {
            "fieldid": 20246,
            "fieldname": "CompanyId",
            "alias": "Quotation to Organization name",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 0,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Organization & End User",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27587,
            "fieldtype": "search",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": "https://water.esrivn.net/CoreTechApi/odataquotation/COMPANYs",
            "columnkey": "CompanyId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": 4900,
            "columncode": "CompanyName",
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": 3249,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null,
            "children": [
                {
                    "fieldid": 20294,
                    "fieldname": "Fax",
                    "alias": "Fax",
                    "isdisplaygrid": "N",
                    "isdisplay": "Y",
                    "displaylength": null,
                    "orderno": 1,
                    "isreadonly": "Y",
                    "fieldlength": null,
                    "vformat": null,
                    "defaultvalue": null,
                    "isrequire": null,
                    "isunique": null,
                    "fieldgroup": "Authorize",
                    "workflowtype": null,
                    "tabid": 3560,
                    "columnid": 27569,
                    "fieldtype": "text",
                    "issearch": null,
                    "issearchtonghop": null,
                    "parentfieldid": 20246,
                    "wherefieldname": "Fax",
                    "columnname": null,
                    "foreigntable": null,
                    "columnkey": "QuotationId",
                    "columndisplay": null,
                    "isfromdomain": null,
                    "domainid": null,
                    "foreigntableid": null,
                    "columncode": null,
                    "displaylogic": null,
                    "calculation": null,
                    "placeholder": null,
                    "columntype": "text",
                    "foreignwindowid": null,
                    "disablelogic": null,
                    "columndohoa": null,
                    "isfilterfield": null,
                    "filterdefaultvalue": null,
                    "treecolumn": null
                }
            ]
        },
        {
            "fieldid": 20263,
            "fieldname": "ContactPointId",
            "alias": "ContactPointId",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 0,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Organization & End User",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27600,
            "fieldtype": "select",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": 20246,
            "wherefieldname": "CompanyId",
            "columnname": null,
            "foreigntable": "https://water.esrivn.net/CoreTechApi/odataquotation/CONTACTPOINTs",
            "columnkey": "ContactPointId",
            "columndisplay": "ContactPointName",
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": 4914,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20264,
            "fieldname": "ContactPointEndpointId",
            "alias": "EndUser Contact Point",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 0,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Organization & End User",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27602,
            "fieldtype": "select",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": 20266,
            "wherefieldname": "CompanyId",
            "columnname": null,
            "foreigntable": "https://water.esrivn.net/CoreTechApi/odataquotation/CONTACTPOINTs",
            "columnkey": "ContactPointId",
            "columndisplay": "ContactPointName",
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": 4914,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20266,
            "fieldname": "CompanyEndpointId",
            "alias": "EndUser Organization",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 0,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Organization & End User",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27603,
            "fieldtype": "search",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": "CompanyId",
            "columnname": null,
            "foreigntable": "https://water.esrivn.net/CoreTechApi/odataquotation/COMPANYs",
            "columnkey": "CompanyId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": 4900,
            "columncode": "CompanyName",
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": 3249,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null,
            "children": [
                {
                    "fieldid": 20297,
                    "fieldname": "EndpointFax",
                    "alias": "EndUser Fax",
                    "isdisplaygrid": "N",
                    "isdisplay": "Y",
                    "displaylength": null,
                    "orderno": 1,
                    "isreadonly": "Y",
                    "fieldlength": null,
                    "vformat": null,
                    "defaultvalue": null,
                    "isrequire": null,
                    "isunique": null,
                    "fieldgroup": "Authorize",
                    "workflowtype": null,
                    "tabid": 3560,
                    "columnid": 27569,
                    "fieldtype": "text",
                    "issearch": null,
                    "issearchtonghop": null,
                    "parentfieldid": 20266,
                    "wherefieldname": "Fax",
                    "columnname": null,
                    "foreigntable": null,
                    "columnkey": "QuotationId",
                    "columndisplay": null,
                    "isfromdomain": null,
                    "domainid": null,
                    "foreigntableid": null,
                    "columncode": null,
                    "displaylogic": null,
                    "calculation": null,
                    "placeholder": null,
                    "columntype": "text",
                    "foreignwindowid": null,
                    "disablelogic": null,
                    "columndohoa": null,
                    "isfilterfield": null,
                    "filterdefaultvalue": null,
                    "treecolumn": null
                }
            ]
        },
        {
            "fieldid": 20244,
            "fieldname": "QuotationNo",
            "alias": "QuotationNo",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 1,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Authorize",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27565,
            "fieldtype": "text",
            "issearch": "Y",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20249,
            "fieldname": "QuotationDate",
            "alias": "QuotationDate",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 1,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": "c$.now()",
            "isrequire": "Y",
            "isunique": null,
            "fieldgroup": "Authorize",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27590,
            "fieldtype": "date",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "date",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20250,
            "fieldname": "QuotationId",
            "alias": "QuotationId",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 1,
            "isreadonly": "Y",
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": "Y",
            "isunique": "Y",
            "fieldgroup": "Authorize",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27567,
            "fieldtype": "number",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20252,
            "fieldname": "UserCreate",
            "alias": "UserCreate",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 1,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": "c$.username",
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Authorize",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27573,
            "fieldtype": "text",
            "issearch": "Y",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20254,
            "fieldname": "UserApproved",
            "alias": "UserApproved",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 1,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": null,
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27572,
            "fieldtype": "text",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20268,
            "fieldname": "DateCreate",
            "alias": "Date Submit",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 1,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": null,
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27575,
            "fieldtype": "date",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "date",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20292,
            "fieldname": "Tel",
            "alias": "Tel",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 1,
            "isreadonly": "Y",
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": "Y",
            "isunique": null,
            "fieldgroup": "Authorize",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27569,
            "fieldtype": "text",
            "issearch": null,
            "issearchtonghop": null,
            "parentfieldid": 20246,
            "wherefieldname": "Tel",
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20293,
            "fieldname": "Email",
            "alias": "Email",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 1,
            "isreadonly": "Y",
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Authorize",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27567,
            "fieldtype": "text",
            "issearch": null,
            "issearchtonghop": null,
            "parentfieldid": 20246,
            "wherefieldname": "Email",
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20294,
            "fieldname": "Fax",
            "alias": "Fax",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 1,
            "isreadonly": "Y",
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Authorize",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27569,
            "fieldtype": "text",
            "issearch": null,
            "issearchtonghop": null,
            "parentfieldid": 20246,
            "wherefieldname": "Fax",
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20295,
            "fieldname": "EndpointTel",
            "alias": "EndUser Tel",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 1,
            "isreadonly": "Y",
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Authorize",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27569,
            "fieldtype": "text",
            "issearch": null,
            "issearchtonghop": null,
            "parentfieldid": 20266,
            "wherefieldname": "Tel",
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20296,
            "fieldname": "EndpointEmail",
            "alias": "EndUser Email",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 1,
            "isreadonly": "Y",
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Authorize",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27569,
            "fieldtype": "text",
            "issearch": null,
            "issearchtonghop": null,
            "parentfieldid": 20266,
            "wherefieldname": "Email",
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20297,
            "fieldname": "EndpointFax",
            "alias": "EndUser Fax",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 1,
            "isreadonly": "Y",
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Authorize",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27569,
            "fieldtype": "text",
            "issearch": null,
            "issearchtonghop": null,
            "parentfieldid": 20266,
            "wherefieldname": "Fax",
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20247,
            "fieldname": "PaymentTermName",
            "alias": "PaymentTermName",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 2,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": "Advance Payment 100%",
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Proposal",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27588,
            "fieldtype": "text",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20261,
            "fieldname": "CurrencyId",
            "alias": "Currency",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 2,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": "1",
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Authorize",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27598,
            "fieldtype": "select",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": "https://water.esrivn.net/CoreTechApi/odataquotation/CURRENCYs",
            "columnkey": "CurrencyId",
            "columndisplay": "CurrencyName",
            "isfromdomain": "N",
            "domainid": 1240,
            "foreigntableid": 4931,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null,
            "children": [
                {
                    "fieldid": 20265,
                    "fieldname": "Exchange",
                    "alias": "Exchange VND",
                    "isdisplaygrid": "Y",
                    "isdisplay": "Y",
                    "displaylength": null,
                    "orderno": 4,
                    "isreadonly": null,
                    "fieldlength": null,
                    "vformat": null,
                    "defaultvalue": "",
                    "isrequire": null,
                    "isunique": null,
                    "fieldgroup": "Authorize",
                    "workflowtype": null,
                    "tabid": 3560,
                    "columnid": 27601,
                    "fieldtype": "number",
                    "issearch": "N",
                    "issearchtonghop": null,
                    "parentfieldid": 20261,
                    "wherefieldname": "TyGia",
                    "columnname": null,
                    "foreigntable": null,
                    "columnkey": "QuotationId",
                    "columndisplay": null,
                    "isfromdomain": null,
                    "domainid": null,
                    "foreigntableid": null,
                    "columncode": null,
                    "displaylogic": "",
                    "calculation": null,
                    "placeholder": null,
                    "columntype": "number",
                    "foreignwindowid": null,
                    "disablelogic": null,
                    "columndohoa": null,
                    "isfilterfield": null,
                    "filterdefaultvalue": null,
                    "treecolumn": null
                }
            ]
        },
        {
            "fieldid": 20270,
            "fieldname": "DateApproved",
            "alias": "DateApproved",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 2,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": null,
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27576,
            "fieldtype": "date",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "date",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20276,
            "fieldname": "ContractNo",
            "alias": "Opportunity No",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 2,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Authorize",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27586,
            "fieldtype": "text",
            "issearch": "Y",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20245,
            "fieldname": "CompanyName",
            "alias": "Organization",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 3,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": null,
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27569,
            "fieldtype": "text",
            "issearch": "Y",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20248,
            "fieldname": "QuotationNetPrice",
            "alias": "Sub Total",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 3,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Price Summary",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27589,
            "fieldtype": "number",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": "_v[0]",
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null,
            "calculationInfos": [
                {
                    "func": "sum",
                    "tab": 3561,
                    "field": "TotalPrice"
                }
            ],
            "children": [
                {
                    "fieldid": 20260,
                    "fieldname": "GrandTotal",
                    "alias": "Net Price",
                    "isdisplaygrid": "Y",
                    "isdisplay": "Y",
                    "displaylength": null,
                    "orderno": 3,
                    "isreadonly": null,
                    "fieldlength": null,
                    "vformat": null,
                    "defaultvalue": null,
                    "isrequire": null,
                    "isunique": null,
                    "fieldgroup": "Price Summary",
                    "workflowtype": null,
                    "tabid": 3560,
                    "columnid": 27597,
                    "fieldtype": "number",
                    "issearch": "N",
                    "issearchtonghop": null,
                    "parentfieldid": null,
                    "wherefieldname": null,
                    "columnname": null,
                    "foreigntable": null,
                    "columnkey": "QuotationId",
                    "columndisplay": null,
                    "isfromdomain": null,
                    "domainid": null,
                    "foreigntableid": null,
                    "columncode": null,
                    "displaylogic": null,
                    "calculation": "_v[0]/(1-_v[1]/100)",
                    "placeholder": null,
                    "columntype": "number",
                    "foreignwindowid": null,
                    "disablelogic": null,
                    "columndohoa": null,
                    "isfilterfield": null,
                    "filterdefaultvalue": null,
                    "treecolumn": null,
                    "children": [
                        {
                            "fieldid": 20256,
                            "fieldname": "QuotationPriceTax",
                            "alias": "QuotationPriceTax (USD)",
                            "isdisplaygrid": "Y",
                            "isdisplay": "Y",
                            "displaylength": null,
                            "orderno": 3,
                            "isreadonly": null,
                            "fieldlength": null,
                            "vformat": "1.2-2",
                            "defaultvalue": "0",
                            "isrequire": null,
                            "isunique": null,
                            "fieldgroup": "Price Summary",
                            "workflowtype": null,
                            "tabid": 3560,
                            "columnid": 27593,
                            "fieldtype": "number",
                            "issearch": "N",
                            "issearchtonghop": null,
                            "parentfieldid": null,
                            "wherefieldname": null,
                            "columnname": null,
                            "foreigntable": null,
                            "columnkey": "QuotationId",
                            "columndisplay": null,
                            "isfromdomain": null,
                            "domainid": null,
                            "foreigntableid": null,
                            "columncode": null,
                            "displaylogic": null,
                            "calculation": "_v[0]/100*_v[1]",
                            "placeholder": null,
                            "columntype": "number",
                            "foreignwindowid": null,
                            "disablelogic": null,
                            "columndohoa": null,
                            "isfilterfield": null,
                            "filterdefaultvalue": null,
                            "treecolumn": null,
                            "calculationInfos": [
                                {
                                    "field": "QuotationTax"
                                },
                                {
                                    "field": "GrandTotal"
                                }
                            ]
                        },
                        {
                            "fieldid": 20257,
                            "fieldname": "QuotationPriceDiscount",
                            "alias": "Price Discount",
                            "isdisplaygrid": "N",
                            "isdisplay": "Y",
                            "displaylength": null,
                            "orderno": 5,
                            "isreadonly": null,
                            "fieldlength": null,
                            "vformat": null,
                            "defaultvalue": null,
                            "isrequire": null,
                            "isunique": null,
                            "fieldgroup": null,
                            "workflowtype": null,
                            "tabid": 3560,
                            "columnid": 27594,
                            "fieldtype": "number",
                            "issearch": "N",
                            "issearchtonghop": null,
                            "parentfieldid": null,
                            "wherefieldname": null,
                            "columnname": null,
                            "foreigntable": null,
                            "columnkey": "QuotationId",
                            "columndisplay": null,
                            "isfromdomain": null,
                            "domainid": null,
                            "foreigntableid": null,
                            "columncode": null,
                            "displaylogic": null,
                            "calculation": "_v[0]*_v[1]/100",
                            "placeholder": null,
                            "columntype": "number",
                            "foreignwindowid": null,
                            "disablelogic": null,
                            "columndohoa": null,
                            "isfilterfield": null,
                            "filterdefaultvalue": null,
                            "treecolumn": null,
                            "calculationInfos": [
                                {
                                    "field": "GrandTotal"
                                },
                                {
                                    "field": "QuotationDiscount"
                                }
                            ]
                        }
                    ],
                    "calculationInfos": [
                        {
                            "field": "QuotationNetPrice"
                        },
                        {
                            "field": "QuotationTax"
                        }
                    ]
                }
            ]
        },
        {
            "fieldid": 20251,
            "fieldname": "QuotationDiscount",
            "alias": "QuotationDiscount",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 3,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Price Summary",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27591,
            "fieldtype": "number",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null,
            "children": [
                {
                    "fieldid": 20257,
                    "fieldname": "QuotationPriceDiscount",
                    "alias": "Price Discount",
                    "isdisplaygrid": "N",
                    "isdisplay": "Y",
                    "displaylength": null,
                    "orderno": 5,
                    "isreadonly": null,
                    "fieldlength": null,
                    "vformat": null,
                    "defaultvalue": null,
                    "isrequire": null,
                    "isunique": null,
                    "fieldgroup": null,
                    "workflowtype": null,
                    "tabid": 3560,
                    "columnid": 27594,
                    "fieldtype": "number",
                    "issearch": "N",
                    "issearchtonghop": null,
                    "parentfieldid": null,
                    "wherefieldname": null,
                    "columnname": null,
                    "foreigntable": null,
                    "columnkey": "QuotationId",
                    "columndisplay": null,
                    "isfromdomain": null,
                    "domainid": null,
                    "foreigntableid": null,
                    "columncode": null,
                    "displaylogic": null,
                    "calculation": "_v[0]*_v[1]/100",
                    "placeholder": null,
                    "columntype": "number",
                    "foreignwindowid": null,
                    "disablelogic": null,
                    "columndohoa": null,
                    "isfilterfield": null,
                    "filterdefaultvalue": null,
                    "treecolumn": null,
                    "calculationInfos": [
                        {
                            "field": "GrandTotal"
                        },
                        {
                            "field": "QuotationDiscount"
                        }
                    ]
                }
            ]
        },
        {
            "fieldid": 20255,
            "fieldname": "QuotationTax",
            "alias": "No. Tax(%)",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 3,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": "0",
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Price Summary",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27592,
            "fieldtype": "number",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null,
            "children": [
                {
                    "fieldid": 20256,
                    "fieldname": "QuotationPriceTax",
                    "alias": "QuotationPriceTax (USD)",
                    "isdisplaygrid": "Y",
                    "isdisplay": "Y",
                    "displaylength": null,
                    "orderno": 3,
                    "isreadonly": null,
                    "fieldlength": null,
                    "vformat": "1.2-2",
                    "defaultvalue": "0",
                    "isrequire": null,
                    "isunique": null,
                    "fieldgroup": "Price Summary",
                    "workflowtype": null,
                    "tabid": 3560,
                    "columnid": 27593,
                    "fieldtype": "number",
                    "issearch": "N",
                    "issearchtonghop": null,
                    "parentfieldid": null,
                    "wherefieldname": null,
                    "columnname": null,
                    "foreigntable": null,
                    "columnkey": "QuotationId",
                    "columndisplay": null,
                    "isfromdomain": null,
                    "domainid": null,
                    "foreigntableid": null,
                    "columncode": null,
                    "displaylogic": null,
                    "calculation": "_v[0]/100*_v[1]",
                    "placeholder": null,
                    "columntype": "number",
                    "foreignwindowid": null,
                    "disablelogic": null,
                    "columndohoa": null,
                    "isfilterfield": null,
                    "filterdefaultvalue": null,
                    "treecolumn": null,
                    "calculationInfos": [
                        {
                            "field": "QuotationTax"
                        },
                        {
                            "field": "GrandTotal"
                        }
                    ]
                },
                {
                    "fieldid": 20260,
                    "fieldname": "GrandTotal",
                    "alias": "Net Price",
                    "isdisplaygrid": "Y",
                    "isdisplay": "Y",
                    "displaylength": null,
                    "orderno": 3,
                    "isreadonly": null,
                    "fieldlength": null,
                    "vformat": null,
                    "defaultvalue": null,
                    "isrequire": null,
                    "isunique": null,
                    "fieldgroup": "Price Summary",
                    "workflowtype": null,
                    "tabid": 3560,
                    "columnid": 27597,
                    "fieldtype": "number",
                    "issearch": "N",
                    "issearchtonghop": null,
                    "parentfieldid": null,
                    "wherefieldname": null,
                    "columnname": null,
                    "foreigntable": null,
                    "columnkey": "QuotationId",
                    "columndisplay": null,
                    "isfromdomain": null,
                    "domainid": null,
                    "foreigntableid": null,
                    "columncode": null,
                    "displaylogic": null,
                    "calculation": "_v[0]/(1-_v[1]/100)",
                    "placeholder": null,
                    "columntype": "number",
                    "foreignwindowid": null,
                    "disablelogic": null,
                    "columndohoa": null,
                    "isfilterfield": null,
                    "filterdefaultvalue": null,
                    "treecolumn": null,
                    "children": [
                        {
                            "fieldid": 20256,
                            "fieldname": "QuotationPriceTax",
                            "alias": "QuotationPriceTax (USD)",
                            "isdisplaygrid": "Y",
                            "isdisplay": "Y",
                            "displaylength": null,
                            "orderno": 3,
                            "isreadonly": null,
                            "fieldlength": null,
                            "vformat": "1.2-2",
                            "defaultvalue": "0",
                            "isrequire": null,
                            "isunique": null,
                            "fieldgroup": "Price Summary",
                            "workflowtype": null,
                            "tabid": 3560,
                            "columnid": 27593,
                            "fieldtype": "number",
                            "issearch": "N",
                            "issearchtonghop": null,
                            "parentfieldid": null,
                            "wherefieldname": null,
                            "columnname": null,
                            "foreigntable": null,
                            "columnkey": "QuotationId",
                            "columndisplay": null,
                            "isfromdomain": null,
                            "domainid": null,
                            "foreigntableid": null,
                            "columncode": null,
                            "displaylogic": null,
                            "calculation": "_v[0]/100*_v[1]",
                            "placeholder": null,
                            "columntype": "number",
                            "foreignwindowid": null,
                            "disablelogic": null,
                            "columndohoa": null,
                            "isfilterfield": null,
                            "filterdefaultvalue": null,
                            "treecolumn": null,
                            "calculationInfos": [
                                {
                                    "field": "QuotationTax"
                                },
                                {
                                    "field": "GrandTotal"
                                }
                            ]
                        },
                        {
                            "fieldid": 20257,
                            "fieldname": "QuotationPriceDiscount",
                            "alias": "Price Discount",
                            "isdisplaygrid": "N",
                            "isdisplay": "Y",
                            "displaylength": null,
                            "orderno": 5,
                            "isreadonly": null,
                            "fieldlength": null,
                            "vformat": null,
                            "defaultvalue": null,
                            "isrequire": null,
                            "isunique": null,
                            "fieldgroup": null,
                            "workflowtype": null,
                            "tabid": 3560,
                            "columnid": 27594,
                            "fieldtype": "number",
                            "issearch": "N",
                            "issearchtonghop": null,
                            "parentfieldid": null,
                            "wherefieldname": null,
                            "columnname": null,
                            "foreigntable": null,
                            "columnkey": "QuotationId",
                            "columndisplay": null,
                            "isfromdomain": null,
                            "domainid": null,
                            "foreigntableid": null,
                            "columncode": null,
                            "displaylogic": null,
                            "calculation": "_v[0]*_v[1]/100",
                            "placeholder": null,
                            "columntype": "number",
                            "foreignwindowid": null,
                            "disablelogic": null,
                            "columndohoa": null,
                            "isfilterfield": null,
                            "filterdefaultvalue": null,
                            "treecolumn": null,
                            "calculationInfos": [
                                {
                                    "field": "GrandTotal"
                                },
                                {
                                    "field": "QuotationDiscount"
                                }
                            ]
                        }
                    ],
                    "calculationInfos": [
                        {
                            "field": "QuotationNetPrice"
                        },
                        {
                            "field": "QuotationTax"
                        }
                    ]
                }
            ]
        },
        {
            "fieldid": 20256,
            "fieldname": "QuotationPriceTax",
            "alias": "QuotationPriceTax (USD)",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 3,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": "1.2-2",
            "defaultvalue": "0",
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Price Summary",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27593,
            "fieldtype": "number",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": "_v[0]/100*_v[1]",
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null,
            "calculationInfos": [
                {
                    "field": "QuotationTax"
                },
                {
                    "field": "GrandTotal"
                }
            ]
        },
        {
            "fieldid": 20260,
            "fieldname": "GrandTotal",
            "alias": "Net Price",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 3,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Price Summary",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27597,
            "fieldtype": "number",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": "_v[0]/(1-_v[1]/100)",
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null,
            "children": [
                {
                    "fieldid": 20256,
                    "fieldname": "QuotationPriceTax",
                    "alias": "QuotationPriceTax (USD)",
                    "isdisplaygrid": "Y",
                    "isdisplay": "Y",
                    "displaylength": null,
                    "orderno": 3,
                    "isreadonly": null,
                    "fieldlength": null,
                    "vformat": "1.2-2",
                    "defaultvalue": "0",
                    "isrequire": null,
                    "isunique": null,
                    "fieldgroup": "Price Summary",
                    "workflowtype": null,
                    "tabid": 3560,
                    "columnid": 27593,
                    "fieldtype": "number",
                    "issearch": "N",
                    "issearchtonghop": null,
                    "parentfieldid": null,
                    "wherefieldname": null,
                    "columnname": null,
                    "foreigntable": null,
                    "columnkey": "QuotationId",
                    "columndisplay": null,
                    "isfromdomain": null,
                    "domainid": null,
                    "foreigntableid": null,
                    "columncode": null,
                    "displaylogic": null,
                    "calculation": "_v[0]/100*_v[1]",
                    "placeholder": null,
                    "columntype": "number",
                    "foreignwindowid": null,
                    "disablelogic": null,
                    "columndohoa": null,
                    "isfilterfield": null,
                    "filterdefaultvalue": null,
                    "treecolumn": null,
                    "calculationInfos": [
                        {
                            "field": "QuotationTax"
                        },
                        {
                            "field": "GrandTotal"
                        }
                    ]
                },
                {
                    "fieldid": 20257,
                    "fieldname": "QuotationPriceDiscount",
                    "alias": "Price Discount",
                    "isdisplaygrid": "N",
                    "isdisplay": "Y",
                    "displaylength": null,
                    "orderno": 5,
                    "isreadonly": null,
                    "fieldlength": null,
                    "vformat": null,
                    "defaultvalue": null,
                    "isrequire": null,
                    "isunique": null,
                    "fieldgroup": null,
                    "workflowtype": null,
                    "tabid": 3560,
                    "columnid": 27594,
                    "fieldtype": "number",
                    "issearch": "N",
                    "issearchtonghop": null,
                    "parentfieldid": null,
                    "wherefieldname": null,
                    "columnname": null,
                    "foreigntable": null,
                    "columnkey": "QuotationId",
                    "columndisplay": null,
                    "isfromdomain": null,
                    "domainid": null,
                    "foreigntableid": null,
                    "columncode": null,
                    "displaylogic": null,
                    "calculation": "_v[0]*_v[1]/100",
                    "placeholder": null,
                    "columntype": "number",
                    "foreignwindowid": null,
                    "disablelogic": null,
                    "columndohoa": null,
                    "isfilterfield": null,
                    "filterdefaultvalue": null,
                    "treecolumn": null,
                    "calculationInfos": [
                        {
                            "field": "GrandTotal"
                        },
                        {
                            "field": "QuotationDiscount"
                        }
                    ]
                }
            ],
            "calculationInfos": [
                {
                    "field": "QuotationNetPrice"
                },
                {
                    "field": "QuotationTax"
                }
            ]
        },
        {
            "fieldid": 20253,
            "fieldname": "StatusId",
            "alias": "StatusId",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 4,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": "1",
            "isrequire": null,
            "isunique": null,
            "fieldgroup": null,
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27570,
            "fieldtype": "number",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": "Y",
            "domainid": 1244,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20258,
            "fieldname": "DayValidId",
            "alias": "Days",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 4,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": "1",
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Proposal",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27595,
            "fieldtype": "select",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": "Y",
            "domainid": 1237,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20259,
            "fieldname": "WarrantyPeriodId",
            "alias": "Year or Month",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 4,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": "3",
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Proposal",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27596,
            "fieldtype": "select",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": "Y",
            "domainid": 1237,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20262,
            "fieldname": "Remark",
            "alias": "Remark",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 4,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Price Summary",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27599,
            "fieldtype": "textarea",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20265,
            "fieldname": "Exchange",
            "alias": "Exchange VND",
            "isdisplaygrid": "Y",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 4,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": "",
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Authorize",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27601,
            "fieldtype": "number",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": 20261,
            "wherefieldname": "TyGia",
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": "",
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20271,
            "fieldname": "DayValid",
            "alias": "Day Valid",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 4,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Proposal",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27581,
            "fieldtype": "number",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20272,
            "fieldname": "WarrantyPeriod",
            "alias": "Warranty Period",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 4,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Proposal",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27583,
            "fieldtype": "number",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": "Y",
            "domainid": 1237,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20273,
            "fieldname": "Delivery",
            "alias": "Delivery (Day)",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 4,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Proposal",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27582,
            "fieldtype": "number",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20274,
            "fieldname": "Note",
            "alias": "Quotation Note",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 4,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": "Proposal",
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27584,
            "fieldtype": "textarea",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20257,
            "fieldname": "QuotationPriceDiscount",
            "alias": "Price Discount",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 5,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": null,
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27594,
            "fieldtype": "number",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": "_v[0]*_v[1]/100",
            "placeholder": null,
            "columntype": "number",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null,
            "calculationInfos": [
                {
                    "field": "GrandTotal"
                },
                {
                    "field": "QuotationDiscount"
                }
            ]
        },
        {
            "fieldid": 20267,
            "fieldname": "UserReject",
            "alias": "UserReject",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 7,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": null,
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27574,
            "fieldtype": "text",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20269,
            "fieldname": "DateReject",
            "alias": "DateReject",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 10,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": null,
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27580,
            "fieldtype": "date",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "date",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        },
        {
            "fieldid": 20275,
            "fieldname": "AdditionalInfo",
            "alias": "AdditionalInfo",
            "isdisplaygrid": "N",
            "isdisplay": "Y",
            "displaylength": null,
            "orderno": 14,
            "isreadonly": null,
            "fieldlength": null,
            "vformat": null,
            "defaultvalue": null,
            "isrequire": null,
            "isunique": null,
            "fieldgroup": null,
            "workflowtype": null,
            "tabid": 3560,
            "columnid": 27585,
            "fieldtype": "text",
            "issearch": "N",
            "issearchtonghop": null,
            "parentfieldid": null,
            "wherefieldname": null,
            "columnname": null,
            "foreigntable": null,
            "columnkey": "QuotationId",
            "columndisplay": null,
            "isfromdomain": null,
            "domainid": null,
            "foreigntableid": null,
            "columncode": null,
            "displaylogic": null,
            "calculation": null,
            "placeholder": null,
            "columntype": "text",
            "foreignwindowid": null,
            "disablelogic": null,
            "columndohoa": null,
            "isfilterfield": null,
            "filterdefaultvalue": null,
            "treecolumn": null
        }
    ]
}